### ISSUE TITLE
Unable to run `vite build`

### ISSUE THREAD

**Issue by narskidan** [urbit/vite-plugin-urbit#1]
For some reason, I'm unable to build anything using this plugin. Below is my attempt to build the default `npx @urbit/create-landscape-app` project from App School.

```
➜  Code npx @urbit/create-landscape-app

✔ What should we call your application? … 
✔ Looks like a directory already exists called "". Where should your app be placed instead? … play
✔ What URL do you use to access Urbit? … http://127.0.0.1:8080
All done, switch to the "play" directory to get started.
Happy hacking!
➜  Code cd play/  
➜  play cd ui
➜  ui npm i
npm WARN deprecated vite-plugin-rewrite-all@1.0.2: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.

added 197 packages, and audited 198 packages in 22s

38 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
➜  ui npm run build

> build
> vite build

failed to load config from /Users/eliana/Documents/Code/play/ui/vite.config.js
error during build:
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/eliana/Documents/Code/play/ui/node_modules/vite-plugin-rewrite-all/dist/index.mjs not supported.
Instead change the require of /Users/eliana/Documents/Code/play/ui/node_modules/vite-plugin-rewrite-all/dist/index.mjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/eliana/Documents/Code/play/ui/node_modules/@urbit/vite-plugin-urbit/dist/index.js:30:49)
    at Object._require.extensions.<computed> [as .js] (file:///Users/eliana/Documents/Code/play/ui/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:66358:17)
    at Object.<anonymous> (/Users/eliana/Documents/Code/play/ui/vite.config.js:37:32)
    at Object._require.extensions.<computed> [as .js] (file:///Users/eliana/Documents/Code/play/ui/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:66355:24)
    at loadConfigFromBundledFile (file:///Users/eliana/Documents/Code/play/ui/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:66363:21)
    at async loadConfigFromFile (file:///Users/eliana/Documents/Code/play/ui/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:66186:28)
    at async resolveConfig (file:///Users/eliana/Documents/Code/play/ui/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:65782:28)
    at async build (file:///Users/eliana/Documents/Code/play/ui/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:47926:20)
    at async CAC.<anonymous> (file:///Users/eliana/Documents/Code/play/ui/node_modules/vite/dist/node/cli.js:842:9)
➜  ui 
```

Here are my versions of things:

```
➜  ui node --version
v16.20.2
➜  ui npx vite --version
vite/4.5.3 darwin-arm64 node-v16.20.2
```

Any advice is appreciated!

**Comment by youfoundron** [comment]
Running into the same issue
